require("dev.plugins-setup")
require("dev.core.options")
require("dev.core.keymaps")
require("dev.core.colorscheme")
require("dev.plugins.nvim-tree")
require("dev.plugins.nvim-cmp")
require("dev.plugins.lualine")
